name: Deployment
on: 
  workflow_dispatch:
  push:
   branches:
    - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: cache-action
        uses: ./.github/actions/cache-deps
        with:
          cache-file: 'package-lock.json'
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: cache-action
        id: cache-action
        uses: ./.github/actions/cache-deps
        with:
          cache-file: 'package-lock.json'        
      - name: print cache status
        run: ' echo Cache status: ${{ steps.cache-action.outputs.cache-status }} '
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: cache-action
        uses: ./.github/actions/cache-deps
        with:
          cache-file: 'package-lock.json'      
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."